name: docker-image-build

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches:
      - "main"

  # Allow mannually trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Checkout to the branch
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20.x"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: saggiyogesh1/logger-stresser

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          username: saggiyogesh1
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v4
        with:
          # platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
